config/routes.rb
Rails.application.routes.draw do
  resources :events
  post "/new_ticket", to: 'dashboard#create_ticket'
  delete "/destroy_ticket", to: 'dashboard#destroy_ticket'
  devise_for :users
  root to: 'dashboard#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :show, Event
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_many   :tickets, dependent: :destroy
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, dependent: :destroy
  has_many :tickets, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource :event, :only => :index

  def index
    @events = Event.all
    @tickets = Ticket.where(user_id: current_user.id)
  end

  def create_ticket
    @ticket = Ticket.new(event_id: params["event_id"])
    @ticket.user_id = current_user.id
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to root_path, notice: 'El Ticket Fue Creado.' }
        format.json { render root_path, status: :created, location: @ticket }
      else
        format.html { render root_path }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy_ticket
    @ticket = Ticket.find(params[:id])
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to root_path, alert: 'El Ticket fue Eliminado.' }
      format.json { head :no_content }
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource

  def new
    @event = Event.new
  end

  def edit
  end

  def create
    @event = Event.new(event_params)
    @event.user_id = current_user.id

    respond_to do |format|
      if @event.save
        format.html { redirect_to root_path, notice: 'El Evento fue creado.' }
        format.json { render root_path, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to root_path, notice: 'El Evento fue Actualizado.' }
        format.json { render root_path, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to root_path, alert: 'El Evento fue Eliminado.' }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :category, :description, :price, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/dashboard/index.html.erb
<div class="container-fluid pb-4">
  <div class="card">
    <div class="card-header text-center">
      <div class="d-flex justify-content-center">
        Eventos
      </div>
    </div>
    <div class="card-body">
      <%- if current_user.admin?%>
        <div class="container-fluid pb-2">
          <div class="d-flex justify-content-end">
            <%= link_to new_event_path do %>
              <button type="button" class="btn btn-outline-success">Nuevo Evento</button>
            <% end %>
          </div>
        </div>
      <% end %>
      <div class="container-fluid">
        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">Nombre</th>
              <th scope="col">Categoria</th>
              <th scope="col">Descripcion</th>
              <th scope="col">Precio</th>
              <th scope="col">Acciones</th>
            </tr>
          </thead>
          <tbody>
            <% @events.each do |event| %>
              <tr>
                <th><%= event.name %></th>
                <td><%= event.category %></td>
                <td><%= event.description %></td>
                <td><%= event.price %></td>
                <td>
                  <%- if current_user.admin? %>
                    <div class="d-flex justify-contetn-center">
                      <%= link_to edit_event_path(event) do %>
                      <button type="button" class="btn btn-outline-info">Editar</button>
                      <% end %>
                      <%= link_to event, method: :delete, data: { Confirm: "Desea Eliminar el Evento" }, class: "pl-1" do %>
                        <button type="button" class="btn btn-outline-danger">Eliminar</button>
                      <% end %>  
                    </div>
                  <% else %>
                    <div class="d-flex justify-contetn-center">
                      <%= link_to new_ticket_path(event_id: event.id), method: :post do %>
                      <button type="button" class="btn btn-outline-success">Comprar Ticket</button>
                      <% end %>  
                    </div>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%- unless current_user.admin? %>
  <div class="container-fluid pt-4">
    <div class="card">
      <div class="card-header text-center">
        <div class="d-flex justify-content-center">
          Tickets Comprados
        </div>
      </div>
      <div class="card-body">
        <div class="container-fluid">
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Ticket #</th>
                <th scope="col">Nombre del Evento</th>
                <th scope="col">Descripcion del Evento</th>
                <th scope="col">Precio del Ticket</th>
                <th scope="col">Acciones</th>
              </tr>
            </thead>
            <tbody>
              <% @tickets.each do |ticket| %>
                <tr>
                  <th><%= ticket.id %></th>
                  <td><%= ticket.event.category %></td>
                  <td><%= ticket.event.description %></td>
                  <td><%= ticket.event.price %></td>
                  <td>
                    <div class="d-flex justify-contetn-center">
                      <%= link_to destroy_ticket_path(id: ticket.id), method: :delete, data: { Confirm: "Desea Eliminar el Ticket" }, class: "pl-1" do %>
                        <button type="button" class="btn btn-outline-danger">Eliminar</button>
                      <% end %>
                    </div>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/events/_form.html.erb
<div class="container-fluid">
  <%= form_with(model: event, local: true) do |form|  %>
    <% if event.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

        <ul>
          <% event.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.text_field :name, class: "form-control", placeholder: "Nombre" %>
      </div>
      <div class="form-group col-md-6">
        <%= form.text_field :category, class: "form-control", placeholder: "Categoria" %>
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-6">
        <%= form.text_field :description, class: "form-control", placeholder: "Descripcion" %>
      </div>
      <div class="form-group col-md-6">
        <%= form.number_field :price, class: "form-control", placeholder: "Precio" %>
      </div>
    </div>
    <div class="d-flex justify-content-end">
      <%= form.submit "#{@event.new_record? ? "Crear" : "Actualizar" }", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/events/edit.html.erb
<div class="container-fluid">
  <div class="card">
    <div class="card-header text-center">
      <div class="d-flex justify-content-start">
        <%= link_to 'Back', root_path %>
      </div>
      <div class="d-flex justify-content-center">
        Editar Evento
      </div>
    </div>
    <div class="card-body">
      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container-fluid">
  <div class="card">
    <div class="card-header text-center">
      <div class="d-flex justify-content-start">
        <%= link_to 'Back', root_path %>
      </div>
      <div class="d-flex justify-content-center">
        Nuevo Evento
      </div>
    </div>
    <div class="card-body">
      <%= render 'form', event: @event %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EventProducer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render template: './layouts/navbar' %>
    <% if notice.present? %>
      <p class="notice alert alert-success"><%= notice %></p>
    <% elsif alert.present? %>
      <p class="alert alert-danger" role="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "EVENTIFY", root_path, class: "navbar-brand" %>

  <% if user_signed_in?%>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to "Cuenta", edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= button_to('Cerrar Sesion', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger")%>
            </li>
        </ul>
      </div>
  <% end %>
</nav>